# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CHROMEOS_KERNEL_CONFIG="/mnt/host/source/src/overlays/overlay-arm64-openfyde_vmware/kconfig/vmware-arm64-r138-def_r1"

CHROMEOS_KERNEL_ARCH="arm64"
BOARD_COMPILER_FLAGS="-march=armv8-a+crc+crypto"
#BOARD_COMPILER_FLAGS="-march=armv8-a"
BOARD_RUSTFLAGS="-Ctarget-feature=+armv8-a,+crc,+aes,+neon,+sha2"
#BOARD_RUSTFLAGS=""
#LDFLAGS="-z max-page-size=0x10000 -Wl,--fix-cortex-a53-843419"
USE="${USE} march_armv8-a"

USE="${USE} containers device_jail"
USE="${USE} -os_install_service"

USE="${USE} legacy_keyboard legacy_power_button ac_power"

# Enable all optional features on generic overlays.
USE="${USE} buffet peerd direncryption"

USE="${USE} kernel-6_6 watchdog"
USE="${USE} -chromeless_tests containers"
USE="${USE} vtpm_proxy -video_capture_use_gpu_memory_buffer"
#USE="${USE} tpm-emulator"
USE="${USE} fydeos_store"
USE="${USE} fixcgroup"
USE="${USE} -tpm tpm2 tpm2_simulator direncription_allow_v2 tpm2_simulator_manufacturer"
USE="${USE} tpm_insecure_fallback"
USE="${USE} selinux_experimental nvme mosys_platform_arm -nacl"
#PORTAGE_BINHOST is pulled in from prebuilt.conf
ACCEPT_LICENSE="*"
#TTY_CONSOLE="ttyS0"
#CHROME_DEV_FLAGS="${CHROME_DEV_FLAGS} --remote-debugging-port=9229 --disable-es3-gl-context"
CHROME_DEV_FLAGS="${CHROME_DEV_FLAGS} --remote-debugging-port=9229 --drm-virtual-connector-is-external --enable-zero-copy"
CPU_FLAGS_ARM="v8 vfpv3 vfpv4 neon vfp"
